// the max size of the queue
const {Client} = require('discord.js');
const {version} = require('../../package.json');
const servers = {};
// the db bot instance
const bot = new Client();
// the id of the bot
const botID = '730350452268597300';
// boolean for dev process - used for debugging, default is false
let startupDevMode = process.argv[2] === '--dev';
// the build number - autogenerated using the version, last two numbers are configurable
const buildNo = version.split('.').map(x => (x.length < 2 ? `0${x}` : x)).join('') + '02';
// max queue size
const MAX_QUEUE_S = 500;
// active process timeout
const checkActiveMS = 600000;
// number of active processes
const setOfBotsOn = new Set();
// commands frequency
const commandsMap = new Map();
// What's playing, uses voice channel id
const whatspMap = new Map();
// The video stream, uses voice channel id
const dispatcherMap = new Map();
// The status of a dispatcher, either true for paused or false for playing
const dispatcherMapStatus = new Map();
// open.spotify.com
const SPOTIFY_BASE_LINK = 'open.spotify.com';
// soundcloud.com
const SOUNDCLOUD_BASE_LINK = 'soundcloud.com';
// twitch.tv
const TWITCH_BASE_LINK = 'twitch.tv';
// 45 minutes
const LEAVE_VC_TIMEOUT = 2700000;
/**
 * Enum - Acceptable link sources.
 * @type {{TWITCH: string, SOUNDCLOUD: string, SPOTIFY: string, YOUTUBE: string}}
 */
const StreamType = {
  SOUNDCLOUD: 'sc',
  SPOTIFY: 'sp',
  YOUTUBE: 'yt',
  TWITCH: 'tw'
};

module.exports = {
  MAX_QUEUE_S, servers, bot, checkActiveMS, setOfBotsOn, commandsMap, whatspMap, dispatcherMap, dispatcherMapStatus,
  botID, SPOTIFY_BASE_LINK, SOUNDCLOUD_BASE_LINK, TWITCH_BASE_LINK, LEAVE_VC_TIMEOUT, StreamType, startupDevMode,
  buildNo
};
